version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # За потреби можна задати додаткові змінні
      DJANGO_SETTINGS_MODULE: shopproject.settings
    command: >
      sh -c "python manage.py migrate --no-input &&
             python manage.py runserver 0.0.0.0:8000"
