name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for build cache support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t shopapp:ci .

      # Run database migrations
      - name: Apply migrations
        run: |
          docker run --rm shopapp:ci python manage.py migrate --no-input

      # Execute the test suite
      - name: Run tests
        run: |
          docker run --rm shopapp:ci python manage.py test --verbosity=2
